version: "3.9"

services:
  elasticsearch:
    container_name: es-01
    image: elasticsearch:8.5.1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    networks:
      - es-net
    ports:
      - 9200:9200

  kibana:
    container_name: kib-01
    image: kibana:8.5.1
    volumes:
      - ./kibanadata:/usr/share/kibana/data
    environment:
      - ELASTICSEARCH_HOSTS=http://es-01:9200
    networks:
      - es-net
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601
      
volumes:
  esdata:
    driver: local
  # kibanadata:
  #   driver: local

networks:
  es-net:
    driver: bridge